"""add audit fields

Revision ID: 49c2b084f178
Revises: 04a3fde24a44
Create Date: 2025-11-30 12:43:49.070435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c2b084f178'
down_revision: Union[str, Sequence[str], None] = '04a3fde24a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('modules', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('modules', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('modules', sa.Column('updater_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modules', 'users', ['updater_id'], ['id'])
    op.create_foreign_key(None, 'modules', 'users', ['creator_id'], ['id'])
    op.add_column('page_elements', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('page_elements', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('page_elements', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('page_elements', sa.Column('updater_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'page_elements', 'users', ['updater_id'], ['id'])
    op.create_foreign_key(None, 'page_elements', 'users', ['creator_id'], ['id'])
    op.add_column('pages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('pages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pages', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('pages', sa.Column('updater_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pages', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'pages', 'users', ['updater_id'], ['id'])
    op.add_column('test_cases', sa.Column('updater_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_cases', 'users', ['updater_id'], ['id'])
    op.add_column('test_suites', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('test_suites', sa.Column('updater_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_suites', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'test_suites', 'users', ['updater_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_suites', type_='foreignkey')
    op.drop_constraint(None, 'test_suites', type_='foreignkey')
    op.drop_column('test_suites', 'updater_id')
    op.drop_column('test_suites', 'creator_id')
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_column('test_cases', 'updater_id')
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.drop_column('pages', 'updater_id')
    op.drop_column('pages', 'creator_id')
    op.drop_column('pages', 'updated_at')
    op.drop_column('pages', 'created_at')
    op.drop_constraint(None, 'page_elements', type_='foreignkey')
    op.drop_constraint(None, 'page_elements', type_='foreignkey')
    op.drop_column('page_elements', 'updater_id')
    op.drop_column('page_elements', 'creator_id')
    op.drop_column('page_elements', 'updated_at')
    op.drop_column('page_elements', 'created_at')
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_column('modules', 'updater_id')
    op.drop_column('modules', 'creator_id')
    op.drop_column('modules', 'updated_at')
    op.drop_column('modules', 'created_at')
    # ### end Alembic commands ###
