"""add_metadata_json_to_page_element

Revision ID: b9594e57f1d3
Revises: 49c2b084f178
Create Date: 2026-03-01 14:33:26.598054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9594e57f1d3'
down_revision: Union[str, Sequence[str], None] = '49c2b084f178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_elements', sa.Column('metadata_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_elements', 'metadata_json')
    # ### end Alembic commands ###
